FROM nginx:1.19.5-alpine

#Aqui estou removendo as configuracoes padrao do nginx
RUN rm /etc/nginx/conf.d/default.conf 

#Aqui estou adicionando as minhas configuracoes
COPY ./nginx.conf /etc/nginx/conf.d
